# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wPH692oomDZ7maKB8rlzU14mqVq3tMM
"""

from mcpi_e.minecraft import *

server_address = "Pycraft.yasan.ac:11110"
python_port = 11130
player_name = "a_Emrani"

mc = Minecraft.create(server_address, python_port, player_name)

for y in range(5):
  for x in range(5-y) :
    mc.setblock(x+y+1, y+1, Gold_black)

from mcpi_e.minecraft import *

server_address = "Pycraft.yasan.ac:11110"
python_port = 11130
player_name = "a_Emrani"

mc = Minecraft.create(server_address, python_port, player_name)

for z in range(5):
  for y in rang(5):
    for x in range(5):
      mc.setblock(x+1, y+1, z+1, Gold_black )

from mcpi_e.minecraft import *

server_address = "Pycraft.yasan.ac"
python_port = 11110
player_name = "a_Emrani"

mc = Minecraft.create(server_address, python_port, player_name)

for x in range(10):
  for z in range(10):
    mc.setblock(1,x+1,z+1, Gold_black)